-- apply changes
create table iuaccount (
  id                            bigint generated by default as identity not null,
  email                         varchar(255) not null,
  first_name                    varchar(255) not null,
  last_name                     varchar(255) not null,
  username                      varchar(255) not null,
  when_modified                 timestamp not null,
  when_created                  timestamp not null,
  constraint uq_iuaccount_email unique (email),
  constraint pk_iuaccount primary key (id)
);
comment on table iuaccount is 'Saved response from userinfo endpoint';
comment on column iuaccount.email is 'Subject, or the unique account identifier, should be users email';

create table player (
  id                            bigint generated by default as identity not null,
  uuid                          uuid not null,
  username                      varchar(255) not null,
  account                       bigint not null,
  admin                         boolean default false not null,
  when_modified                 timestamp not null,
  when_created                  timestamp not null,
  constraint uq_player_uuid unique (uuid),
  constraint uq_player_account unique (account),
  constraint pk_player primary key (id)
);
comment on table player is 'Map of in-game players to their IU account';
comment on column player.uuid is 'Minecraft player UUID';
comment on column player.username is 'Players cached username';
comment on column player.admin is 'Is the user an admin?';

-- foreign keys and indices
alter table player add constraint fk_player_account foreign key (account) references iuaccount (id) on delete restrict on update restrict;

